### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by abdulmalikkhan655** [DDihanov/musiQ#10]
Hello, @DDihanovI want to contribute in "musiQ" so i  want to designed a new logo for "musiQ" and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.
if you want i will send you my design

contact me on facebook for fast delivary 
https://www.facebook.com/abdulmalikkhan655

**Comment by ggcarlosr** [comment]
Hello friend, I am also available to join by presenting a logo proposal, and you can have a second option to choose, can I contribute?

**Comment by DDihanov** [comment]
@abdulmalikkhan655 @ggcarlosr sure guys that would be great :). Drop me an email at dimitar.dihanov at gmail.com with your ideas. Thanks for the interest again!

**Comment by abdulmalikkhan655** [comment]
@DDihanov  thanks sir as soon as i will send you my logo design

**Comment by abdulmalikkhan655** [comment]
![11](https://user-images.githubusercontent.com/36396753/40174430-7e6fbbba-59ee-11e8-8474-0af8596e0c07.png)
![12](https://user-images.githubusercontent.com/36396753/40174431-7ede9120-59ee-11e8-86ad-afac3ca76941.png)

hello sir check this logo and select your logo If there's something you want to change, I'll do it.

**Comment by DDihanov** [comment]
Dear Abdul,

thanks for the logos, but I decided to go with the suggestion of another
guy. Don't get me wrong, your logos are awesome and in no way do I want to
offend you with this,
it's just that I think the other logo is more fitting. Thanks for your
interest and keep on rocking the open source world :)!

Best regards,
Dihanov

**Comment by TacoTheDank** [comment]
@DDihanov It's better if you didn't anyway, as you could've gotten a strike from flaticons. This guy takes icons from flaticons and passes them off as his own, and he's been spamming every open-source project with this issue trying to gain cryptocurrency with utopian.io

read this https://github.com/kaeptmblaubaer1000/android-torchlight/issues/3

**Comment by abdulmalikkhan655** [comment]
becarefull guyz @TacoTheDank  is a scammer  so be careful

**Comment by TacoTheDank** [comment]
Keep trying to save yourself bud, no one even trusts you anymore

**Comment by DDihanov** [comment]
@TacoTheDank thanks for the warning :)

**Comment by TacoTheDank** [comment]
No problem. I've been going around the issues he's been creating that people responded to, warning people about him

**Comment by abdulmalikkhan655** [comment]
@DDihanov  becarefull from @TacoTheDank   he is scammer this guys always try to hack my system

**Comment by TacoTheDank** [comment]
You've said nothing of actual value or proof to back up your claims; all you've said was "scammer" over and over lol
