### ISSUE TITLE
App crashes on performing series of events

### ISSUE THREAD

**Issue by neupanedipen** [DDihanov/musiQ#14]
##### Series of events<br>
1. Continue to account without an account.<br>
2. Go to about and dismiss the dialogue box.<br>
3. Click on Profile option.<br>
The app crashes.<br>
#### Expected behavior<br>
The app must be stable when clicking the Profile option after dismissing the About page.<br>
#### Actual behavior<br>
But the app crashes on clicking the Profile option after closing the about page.<br>
#### How to reproduce<br>
1. Install the app and launch it.<br>
2. Continue to the app without an account.<br>
3. Now go to About from left sliding menu and dismiss it.<br>
4. After closing the about page click ob &quot;Profile&quot; option from the left sliding menu.<br>
The app crashes.<br>
* App Version: 1.831<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/OaslS0qNC3w

**Comment by DDihanov** [comment]
Thank you for the issue again, can you please click the "Report" button after the crash so I can get the crash log? Thanks!

**Comment by neupanedipen** [comment]
I have clicked the report option. I hope you have received the logs.

**Comment by DDihanov** [comment]
Hey I think I fixed this with the new 1.844 update. Can you confirm?

**Comment by DDihanov** [comment]
Fixed with the new release.
