### ISSUE TITLE
app crash when click click on Profile after click on  About while using app without account 

### ISSUE THREAD

**Issue by kr-nahid** [DDihanov/musiQ#17]
#### Expected behavior
it should not be crash when click on **Profile** after click on **About** while using  app without account .

#### Actual behavior
when i click on **continue to the library without account...** , it takes me library and when i click on **Profile** after click on **About** this occurs to crash . 

#### How to reproduce
* download the app
* open it 
* then click on **continue to the library without account...** 
* then click on **About** and now click on **Profile**
* note the bug.

> Browser/App version:  [musiQ](https://play.google.com/store/apps/details?id=com.dihanov.musiq&utm_source=github&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1
)  1.842
 Operating system: android 6.0

#### Recording Of The Bug
https://www.youtube.com/watch?v=T_OPI9fvFc8

**Comment by DDihanov** [comment]
Thanks for this. I will look into it.

**Comment by DDihanov** [comment]
Hey I think I fixed it with the 1.844 update, can you confirm?
