### ISSUE TITLE
Remember me not working for saving any user name and password

### ISSUE THREAD

**Issue by kr-nahid** [DDihanov/musiQ#18]
#### Expected behavior
user when click on Remember me it should be save user name and password

#### Actual behavior
when i use my user name and  password and click on Remember me it open account but when i logout nothing user name and password .
#### How to reproduce
* download the app
* open it 
* then put your last fm account and password 
* then click on Remember me and loglin
* now logout from app
* and note the bug

> Browser/App version:  [musiQ](https://play.google.com/store/apps/details?id=com.dihanov.musiq&utm_source=github&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1
)  v1.842
 Operating system: android 6.0

#### Recording Of The Bug
https://www.youtube.com/watch?v=ovcxX0OSNA0

**Comment by DDihanov** [comment]
When you click logout the system deletes your remembered password. But thanks for the report nonetheless =).
