### ISSUE TITLE
Search for friends feature not working

### ISSUE THREAD

**Issue by neupanedipen** [DDihanov/musiQ#20]
Go to Profile>Friends and type a username to search and click enter. But search feature doesn't work.

**Comment by DDihanov** [comment]
Hello and thanks for the report. The program was searching, but the keyboard didn't hide. I fixed this with the new 1.857 release.

**Comment by neupanedipen** [comment]
The program does not seem to be like searching. When I tried to search a friend ( was searching my another last.fm username) no results appear eve after a long time of waiting.
