### ISSUE TITLE
App crashes when adding a track to loved track through now scrobbling

### ISSUE THREAD

**Issue by Olamatto** [DDihanov/musiQ#21]
#### Expected behavior
The application ought to work perfectly well, after clicking on the love track button.

#### Actual behavior
After clicking on the Now scrobbling in the notification bar, while the track details are loading, clicking on the love track button makes the app crash. 

#### How to reproduce
- Download and install the application [here](https://play.google.com/store/apps/details?id=com.dihanov.musiq)
- Switch on your data connection
- Launch the application
- Log in if you already have an account or click on the sign up button if you are yet to get an account 
- Close the application 
- Go to your music player, play any music
- Scroll down your notification, to see the Now scrobbling, click on it
- While the section is loading, scroll down double click on the love track button

Then the app crashes

<hr>

* App version: musiQ 1.857
* Operating system: Android v7.0

#### Recording Of The Bug
https://youtu.be/BgxOAcxBnJ8

**Comment by DDihanov** [comment]
Thank you for hte report. Can you please click on the "Send feedback" button so I can get the crash log? Thanks!

**Comment by Olamatto** [comment]
Ok i will do just that.

**Comment by DDihanov** [comment]
Can you confirm if the new 1.860 release fixes this?
