### ISSUE TITLE
[Version 1.857] - Drawer cannot be opened when the album list area is collapsed.

### ISSUE THREAD

**Issue by tobias-g1** [DDihanov/musiQ#22]
#### Expected Behaviour

The drawer should remain functional in all areas of the application to allow users to navigate the application using the drawer options.

#### Actual Behaviour

The drawer is not triggerable when the album list area is collapsed. 

#### Steps to reproduce

1. From a fresh install (existing will work, but my steps are based on a fresh install). 
2. Launch the application and indicate that you would like to enter the application without signing in. This can be achieved by clicking on the "Or continue to the library without an account" link. 
3. When presented with the warning that some features will not be available, click "continue". 
4. You will be presented with a list of popular artists and shown album artwork, swipe up on the albums until the album area has been fully collapsed (swipe from the bottom of the albums container). 
5. Click on the drawer icon (hamburger) located at the top left of the page. 
6. Note that the icon will not be clickable and the drawer will not function. 

#### Environment

This bug has been tested and replicated on the following devices and Android versions:

##### Device 1

 - Device: Pixel 2
 - Android Version: 8.0
 - Device Type: Emulated
- Application Version: 1.857

##### Device 2
- Device: Motorola 3 (3rd Generation)
- Android Version: 6.0.1
- Device Type: Physical
- Application Version: 1.857

#### Recording of the issue

The following video shows this issue in more detail:

https://www.youtube.com/embed/L1bHO7QzZ8U

**Comment by DDihanov** [comment]
Thanks for the report. It seems the text from the tab layout is overlapping the drawer button. I will look for a possible fix.

**Comment by DDihanov** [comment]
Fixed with new 1.860 release.
