### ISSUE TITLE
Some albums cannot be deleted from the Favorites list, once added.

### ISSUE THREAD

**Issue by shirou-jeff** [DDihanov/musiQ#23]
#### Expected behavior
The user expects to be able to add or delete albums from the Favorites list.
#### Actual behavior
The user cannot add or delete some albums from the Favorites list. Because when I try to add or delete albums from the Favorites list, some of them are not added or cannot be deleted from the list.

#### How to reproduce
- Search some albums and add them to favorites.
- Go to the albums favorite list and try to delete it. 
- close and open the application again. 
- Now we notice that the album recently removed, is again in the albums favorite list.

* App version: MusiQ V 1.857
* Operating system: Android 6.0

#### Recording Of The Bug
https://youtu.be/GlHuZTZBV4w

**Comment by DDihanov** [comment]
Thanks for the report. When you re-launch the application, were the albums in the favorites different than the ones you added?

**Comment by shirou-jeff** [comment]
It is my pleasure, No, after re-launch the albums are still the same.

**Comment by DDihanov** [comment]
I fixed this with 1.860. Took a lot of tweaking, but it should be okay now.
